version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    ports:
      - "8000:8000"
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: my-secret-pw
      DATABASE_NAME: mydatabase
    networks:
      - mysql_network
    depends_on:
      mysql:
        condition: service_healthy
    restart: always

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: mydatabase
    tty: true
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql_network
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-pmy-secret-pw"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

networks:
  mysql_network:
    driver: bridge

volumes:
  mysql_data:
